CREATE TABLE Cohort (
    Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
    Name VARCHAR(55) NOT NULL
);

CREATE TABLE Student (
    Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
    FirstName VARCHAR(55) NOT NULL,
    LastName VARCHAR(55) NOT NULL,
    SlackHandle VARCHAR(55),
    CohortId INTEGER NOT NULL,
    CONSTRAINT CohortId FOREIGN KEY(CohortId) REFERENCES Cohort(Id)
);

CREATE TABLE Exercise (
    Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
    Name VARCHAR(55) NOT NULL,
    Language VARCHAR(55) NOT NULL
);

CREATE TABLE StudentExercises (
    Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
    StudentId INTEGER NOT NULL,
    ExerciseId INTEGER NOT NULL,
    CONSTRAINT ExerciseId FOREIGN KEY(ExerciseId) REFERENCES Exercise(Id),
    CONSTRAINT StudentId FOREIGN KEY(StudentId) REFERENCES Student(Id)
);

CREATE TABLE Instructor (
    Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
    FirstName VARCHAR(55) NOT NULL,
    LastName VARCHAR(55) NOT NULL,
    CohortId INTEGER NOT NULL, 
    SlackHandle VARCHAR(55) NOT NULL,
    Specialty VARCHAR(55) NOT NULL,
    CONSTRAINT InstructorCohortId FOREIGN KEY(CohortId) REFERENCES Cohort(Id)
);





